In [2]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import datetime


def weather_history(code)
    now = datetime.datetime.now()
    month = str(now.month)
    day = str(now.day-7)

#assemble url
    url = 'https://www.wunderground.com/history/airport/' + code + '/2018/' + month + '/' + 'day' + '/WeeklyHistory.html?&reqdb.zip=&reqdb.magic=&reqdb.wmo='
    
    #call and read with BS4
    req = requests.get(url)
    soup = BeautifulSoup(req.text, 'lxml')

    #parse the table
    table = soup('table')[3]
    table_body = table.find_all('tbody')
    table_head = table.find('thead')

    header = []

    for th in table_head.findAll('th'):
        key = th.get_text()
        header.append(key)

    # The first row has an odd sub-header, so it will be left out and re-genreated manually when creating the pandas df
    rows = []
    for tb in table_body[1:]:
        row = []
        for elem in tb.find_all('td'):
            try:
                row.append(float(elem.get_text().strip()))
            except ValueError:
                pass

        rows.append(row)
    #define the column headers
    column_head=[ month,'High Temp','Avg Temp','Low Temp','Low Dew Point','Avg Dew Point','High Dew Point','High Humidity (%)','Avg Humidity (%)','Low HUmidity (%)',
            'High Sea Level Press. (in)','Avg Sea Level Press. (in)','Low Sea Level Press. (in)','High Visibiity (mi)','Avg Visibiity (mi)','Low Visibiity (mi)',
            'High Wind (mph)','Avg High Wind (mph)','Low High Wind (mph)','Precip. (in)']
    df=pd.DataFrame(rows,columns=column_head)
    
    return df

In [34]:
now = datetime.datetime.now()
month = str(now.month)
day = str(now.day-7)
code = 'KSFO'

#assemble url
url = 'https://www.wunderground.com/history/airport/' + code + '/2018/' + month + '/' + 'day' + '/WeeklyHistory.html?&reqdb.zip=&reqdb.magic=&reqdb.wmo='
req = requests.get(url)

#print(req.text)
soup = BeautifulSoup(req.text, 'lxml')
#print(soup.prettify())

In [39]:
req = requests.get(url)
soup = BeautifulSoup(req.text, 'lxml')

table = soup('table')[3]
table_body = table.find_all('tbody')
table_head = table.find('thead')

header = []

for th in table_head.findAll('th'):
    key = th.get_text()
    header.append(key)

# The first row has an odd sub-header, so it will be left out and re-genreated manually when creating the pandas df
rows = []
for tb in table_body[1:]:
    row = []
    for elem in tb.find_all('td'):
        try:
            row.append(float(elem.get_text().strip()))
        except ValueError:
            pass

    rows.append(row)

column_head=[ month,'High Temp','Avg Temp','Low Temp','Low Dew Point','Avg Dew Point','High Dew Point','High Humidity (%)','Avg Humidity (%)','Low HUmidity (%)',
            'High Sea Level Press. (in)','Avg Sea Level Press. (in)','Low Sea Level Press. (in)','High Visibiity (mi)','Avg Visibiity (mi)','Low Visibiity (mi)',
            'High Wind (mph)','Avg High Wind (mph)','Low High Wind (mph)','Precip. (in)']
df=pd.DataFrame(rows,columns=column_head)

,March,High Temp,Avg Temp,Low Temp,Low Dew Point,Avg Dew Point,High Dew Point,High Humidity (%),Avg Humidity (%),Low HUmidity (%),High Sea Level Press. (in),Avg Sea Level Press. (in),Low Sea Level Press. (in),High Visibiity (mi),Avg Visibiity (mi),Low Visibiity (mi),High Wind (mph),Avg High Wind (mph),Low High Wind (mph),Precip. (in)
0,25.0,59.0,50.0,40.0,41.0,38.0,34.0,83.0,63.0,43.0,30.37,30.29,30.19,10.0,10.0,10.0,28.0,9.0,37.0,0.00
1,26.0,54.0,50.0,45.0,44.0,40.0,34.0,80.0,65.0,50.0,30.17,30.00,29.91,10.0,9.0,4.0,31.0,13.0,36.0,0.19
2,27.0,58.0,51.0,44.0,33.0,25.0,19.0,60.0,43.0,26.0,30.14,30.04,29.93,10.0,10.0,10.0,28.0,11.0,33.0,0.00
3,28.0,56.0,49.0,41.0,48.0,42.0,31.0,83.0,71.0,58.0,30.21,30.14,30.05,10.0,10.0,5.0,23.0,9.0,28.0,0.16
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,1.0,59.0,54.0,48.0,51.0,47.0,40.0,89.0,74.0,59.0,30.03,29.88,29.80,10.0,7.0,2.0,33.0,20.0,42.0,1.04
6,2.0,56.0,51.0,45.0,44.0,40.0,36.0,83.0,65.0,47.0,29.96,29.92,29.88,10.0,10.0,4.0,24.0,9.0,31.0,0.18
7,3.0,53.0,48.0,42.0,42.0,39.0,37.0,89.0,76.0,63.0,30.14,30.04,29.96,10.0,10.0,9.0,21.0,8.0,25.0,0.05